### ISSUE TITLE
not loading resources on launch

### ISSUE THREAD

**Issue by prabaharanit** [LearningPool/adapt-contrib-responsiveIframe#14]
i have added this plugin to adapt, to have html 5 interactions in page, which i intend to load through iframe , provided by this plugin.
But when i do preview, the browser is not loading the file , and getting below error in browser console.

00/preview/594a52de22506f5c320f3228/594b77dbe491b6741e4741e7/libraries/jquery.v2.js:3 Not allowed to load local resource: file:///C:/Users/prabaharan.p/Documents/bookmap/images/media_core_captivate-sim_en-US_0000006/index.html

do we have any fix for this?

**Comment by brian-learningpool** [comment]
Hi @prabaharanit, this is a security exception caused by the fact that you have attempted to load a file that's local to your computer, i.e. on your C:\ drive and not on the internet.  You can resolve this if you host your content on a web server and link to that.
